export const GET_POKEMONS_BY_LIMIT = 'GET_POKEMONS_BY_LIMIT';
export const GET_POKEMONS_BY_LIMIT_SUCCESS = 'GET_POKEMONS_BY_LIMIT_SUCCESS';
export const GET_POKEMONS_BY_LIMIT_FAILURE = 'GET_POKEMONS_BY_LIMIT_FAILURE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const RESET_CURRENT_PAGE = 'RESET_CURRENT_PAGE';
